displayName=Penguin Crushers
author=hyperslab
description=Displays far too much information about the crushers in the penguin agility course
tags=agility
version=1.0
plugins=com.example.PenguinCrushersPlugin
build=standard